# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0'

target 'RandomPicker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RandomPicker
pod 'SnapKit'
pod 'Then'
pod 'SAConfettiView'
pod 'Google-Mobile-Ads-SDK'

end
